#!/usr/bin/env python3

"""
Distance-to-TSS analyses for delta H3K9me2 and TE expression.

This script consumes the 1-kb table generated by
H3K9me2_TE_correlation.py and performs the remaining
distance analyses:

1. Calculates the distance from every 1-kb genomic bin to the nearest
   protein-coding transcription start site (TSS).
2. Summarizes delta H3K9me2 across TSS-distance bins in Eu and PCH.
3. Calculates TSS distance, local H3K9me2 signal, and TE expression for
   each annotated TE locus.
4. Summarizes TE expression across TSS-distance bins after separating
   loci with H3K9me2 gain/stability from loci with H3K9me2 loss.
5. Among expressed TE loci, compares local delta H3K9me2 between
   TSS-proximal loci (<2 kb) and TSS-distal loci (>20 kb) using a
   two-sided Mann-Whitney U test.

Required input files:
    H3K9me2_1kb_TE_correlation_results/H3K9_delta_TE_binned_1kb.csv
    w1118_v4_sorted.protein_coding.gtf
    w1118_TE-annotation_onecodetofindthemall_soloTE_chr.bed
    H3K9me2_sperm.RPGC.bw
    H3K9me2_wing.RPGC.bw
    1__spermatocyte.tsv.CPM.bw

The TE annotation coordinates are treated as 1-based inclusive,
matching the original analysis script.

Required Python packages:
    numpy
    pandas
    pyBigWig
    scipy
"""

from __future__ import annotations

import importlib.metadata
import sys
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd
import pyBigWig
from scipy.stats import mannwhitneyu


# ==============================================================================
# 1. Inputs, outputs, and analysis parameters
# ==============================================================================

H3K9_1KB_TABLE = Path(
    "H3K9me2_1kb_TE_correlation_results"
    "/H3K9_delta_TE_binned_1kb.csv"
)

PROTEIN_CODING_GTF = Path(
    "w1118_v4_sorted.protein_coding.gtf"
)

TE_ANNOTATION_BED = Path(
    "w1118_TE-annotation_onecodetofindthemall_soloTE_chr.bed"
)

H3K9_SPERMATOCYTE_BIGWIG = Path(
    "H3K9me2_sperm.RPGC.bw"
)

H3K9_WING_BIGWIG = Path(
    "H3K9me2_wing.RPGC.bw"
)

TE_EXPRESSION_BIGWIG = Path(
    "1__spermatocyte.tsv.CPM.bw"
)

OUTPUT_DIR = Path(
    "H3K9me2_TSS_distance_results"
)

TE_COORDINATES_ARE_ONE_BASED_INCLUSIVE = True

PROXIMAL_DISTANCE_BP = 2_000
DISTAL_DISTANCE_BP = 20_000

DISTANCE_BREAKS_BP = [
    0,
    500,
    1_000,
    2_000,
    5_000,
    10_000,
    20_000,
    50_000,
    np.inf,
]

DISTANCE_LABELS = [
    "0-0.5 kb",
    "0.5-1 kb",
    "1-2 kb",
    "2-5 kb",
    "5-10 kb",
    "10-20 kb",
    "20-50 kb",
    ">=50 kb",
]

COMPARTMENT_ORDER = ("Eu", "PCH", "Telo")
TARGET_CHROMOSOMES = ("2L", "2R", "3L", "3R", "X")

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ==============================================================================
# 2. Helper functions
# ==============================================================================

def require_file(path: Path) -> None:
    """Stop when a required input file is absent."""
    if not path.is_file():
        raise FileNotFoundError(
            f"Required input file not found: {path}"
        )


def canonical_chromosome(name: str) -> str:
    """Remove an optional chr prefix."""
    name = str(name)
    return name[3:] if name.startswith("chr") else name


def chromosome_map(bigwig: pyBigWig.pyBigWig) -> dict[str, str]:
    """Map canonical chromosome names to names used by a bigWig."""
    mapping: dict[str, str] = {}

    for bigwig_name in bigwig.chroms():
        canonical_name = canonical_chromosome(
            bigwig_name
        )

        if canonical_name in mapping:
            raise ValueError(
                "A bigWig contains ambiguous chromosome names for "
                f"{canonical_name}."
            )

        mapping[canonical_name] = bigwig_name

    return mapping


def parse_gene_tss(
    gtf_path: Path,
) -> dict[str, np.ndarray]:
    """
    Parse one TSS coordinate per protein-coding gene from a GTF.

    The supplied GTF is expected to contain gene records only or to have
    already been restricted to protein-coding genes.
    """
    TSS_records: list[tuple[str, int]] = []

    with gtf_path.open() as handle:
        for line_number, line in enumerate(
            handle,
            start=1,
        ):
            if not line.strip() or line.startswith("#"):
                continue

            fields = line.rstrip("\n").split("\t")

            if len(fields) < 9:
                raise ValueError(
                    f"Malformed GTF line {line_number}: fewer than nine columns."
                )

            if fields[2] != "gene":
                continue

            chromosome = canonical_chromosome(
                fields[0]
            )

            if chromosome not in TARGET_CHROMOSOMES:
                continue

            start = int(fields[3])
            end = int(fields[4])
            strand = fields[6]

            if end < start:
                raise ValueError(
                    f"Malformed GTF interval at line {line_number}."
                )

            if strand == "+":
                TSS = start
            elif strand == "-":
                TSS = end
            else:
                raise ValueError(
                    f"Unsupported strand at GTF line {line_number}: {strand}"
                )

            TSS_records.append(
                (chromosome, TSS)
            )

    if not TSS_records:
        raise ValueError(
            "No gene-level TSS records were parsed from the GTF."
        )

    TSS_table = pd.DataFrame(
        TSS_records,
        columns=("chr", "tss"),
    ).drop_duplicates()

    return {
        chromosome: np.sort(
            chromosome_data[
                "tss"
            ].to_numpy(
                dtype=np.int64
            )
        )
        for chromosome, chromosome_data
        in TSS_table.groupby("chr")
    }


def distance_to_nearest_tss(
    chromosome: str,
    positions: np.ndarray,
    TSS_by_chromosome: dict[str, np.ndarray],
) -> np.ndarray:
    """
    Vectorized absolute distance from positions to the nearest TSS.
    """
    positions = np.asarray(
        positions,
        dtype=np.int64,
    )

    if chromosome not in TSS_by_chromosome:
        return np.full(
            len(positions),
            np.nan,
            dtype=float,
        )

    TSS_positions = TSS_by_chromosome[
        chromosome
    ]

    insertion_indices = np.searchsorted(
        TSS_positions,
        positions,
        side="left",
    )

    left_indices = np.clip(
        insertion_indices - 1,
        0,
        len(TSS_positions) - 1,
    )

    right_indices = np.clip(
        insertion_indices,
        0,
        len(TSS_positions) - 1,
    )

    left_distance = np.abs(
        positions
        - TSS_positions[left_indices]
    )

    right_distance = np.abs(
        positions
        - TSS_positions[right_indices]
    )

    return np.minimum(
        left_distance,
        right_distance,
    ).astype(float)


def add_nearest_tss_distance(
    data: pd.DataFrame,
    chromosome_column: str,
    position_column: str,
    TSS_by_chromosome: dict[str, np.ndarray],
) -> pd.Series:
    """Calculate nearest-TSS distance for every row in a table."""
    distances = np.full(
        len(data),
        np.nan,
        dtype=float,
    )

    for chromosome, row_indices in data.groupby(
        chromosome_column,
        sort=False,
    ).indices.items():
        row_indices = np.asarray(
            row_indices,
            dtype=int,
        )

        distances[row_indices] = distance_to_nearest_tss(
            chromosome=str(chromosome),
            positions=data.iloc[
                row_indices
            ][
                position_column
            ].to_numpy(
                dtype=np.int64
            ),
            TSS_by_chromosome=TSS_by_chromosome,
        )

    return pd.Series(
        distances,
        index=data.index,
        dtype=float,
    )


def parse_TE_annotation(
    bed_path: Path,
) -> pd.DataFrame:
    """
    Read the six-column TE annotation and parse family/superfamily/class.

    Expected identifier format:
        contig|start|end|FAMILY:SUPERFAMILY:CLASS|divergence|strand
    """
    TE_table = pd.read_csv(
        bed_path,
        sep="\t",
        header=None,
        usecols=range(6),
        names=(
            "chr",
            "start",
            "end",
            "id",
            "divergence",
            "strand",
        ),
        dtype={
            "chr": str,
            "id": str,
            "strand": str,
        },
    )

    TE_table["chr"] = (
        TE_table["chr"]
        .map(canonical_chromosome)
    )

    TE_table["start"] = pd.to_numeric(
        TE_table["start"],
        errors="raise",
    ).astype(int)

    TE_table["end"] = pd.to_numeric(
        TE_table["end"],
        errors="raise",
    ).astype(int)

    invalid_intervals = (
        TE_table["end"]
        < TE_table["start"]
    )

    if invalid_intervals.any():
        raise ValueError(
            f"{invalid_intervals.sum()} TE intervals have end < start."
        )

    identifier_parts = TE_table[
        "id"
    ].str.split(
        "|",
        regex=False,
    )

    family_information = identifier_parts.map(
        lambda values: (
            values[3]
            if len(values) > 3
            else np.nan
        )
    )

    annotation_parts = family_information.str.split(
        ":",
        regex=False,
    )

    TE_table["TE_family"] = annotation_parts.map(
        lambda values: (
            values[0]
            if isinstance(values, list)
            and len(values) >= 1
            else np.nan
        )
    )

    TE_table["TE_superfamily"] = annotation_parts.map(
        lambda values: (
            values[1]
            if isinstance(values, list)
            and len(values) >= 2
            else np.nan
        )
    )

    TE_table["TE_class"] = annotation_parts.map(
        lambda values: (
            values[-1]
            if isinstance(values, list)
            and len(values) >= 1
            else np.nan
        )
    ).str.upper()

    TE_table["midpoint"] = (
        TE_table["start"]
        + TE_table["end"]
    ) // 2

    return TE_table


def assign_compartment(
    chromosome: str,
    positions: np.ndarray,
) -> np.ndarray:
    """Assign TE midpoints to Eu, PCH, or Telo."""
    boundaries = {
        "2L": (
            (1, 34_496, "Telo"),
            (34_497, 21_806_874, "Eu"),
            (21_806_875, 23_219_612, "PCH"),
        ),
        "2R": (
            (1, 4_651_836, "PCH"),
            (4_651_837, 24_535_303, "Eu"),
            (24_535_304, 24_550_778, "Telo"),
        ),
        "3L": (
            (1, 29_781, "Telo"),
            (29_782, 22_811_581, "Eu"),
            (22_811_582, 27_189_634, "PCH"),
        ),
        "3R": (
            (1, 3_415_214, "PCH"),
            (3_415_215, 31_253_423, "Eu"),
            (31_253_424, 31_281_498, "Telo"),
        ),
        "X": (
            (1, 138_429, "Telo"),
            (138_430, 22_110_469, "Eu"),
            (22_110_470, 22_604_182, "PCH"),
        ),
    }

    output = np.full(
        len(positions),
        None,
        dtype=object,
    )

    if chromosome not in boundaries:
        return output

    for start, end, compartment in boundaries[
        chromosome
    ]:
        in_interval = (
            (positions >= start)
            & (positions <= end)
        )
        output[in_interval] = compartment

    return output


def extract_interval_signals(
    TE_table: pd.DataFrame,
    bigwig_paths: dict[str, Path],
) -> pd.DataFrame:
    """
    Extract mean signal across every TE interval.

    Each bigWig is opened once and reused for all loci.
    """
    handles = {
        signal_name: pyBigWig.open(
            str(path)
        )
        for signal_name, path
        in bigwig_paths.items()
    }

    maps = {
        signal_name: chromosome_map(
            handle
        )
        for signal_name, handle
        in handles.items()
    }

    signal_arrays = {
        signal_name: np.full(
            len(TE_table),
            np.nan,
            dtype=float,
        )
        for signal_name in handles
    }

    try:
        for row_number, row in enumerate(
            TE_table.itertuples(index=False)
        ):
            chromosome = row.chr

            if TE_COORDINATES_ARE_ONE_BASED_INCLUSIVE:
                interval_start = max(
                    0,
                    int(row.start) - 1,
                )
                interval_end = int(row.end)
            else:
                interval_start = max(
                    0,
                    int(row.start),
                )
                interval_end = int(row.end)

            for signal_name, handle in handles.items():
                if chromosome not in maps[
                    signal_name
                ]:
                    continue

                bigwig_chromosome = maps[
                    signal_name
                ][chromosome]

                chromosome_length = int(
                    handle.chroms()[
                        bigwig_chromosome
                    ]
                )

                clipped_end = min(
                    interval_end,
                    chromosome_length,
                )

                if clipped_end <= interval_start:
                    continue

                value = handle.stats(
                    bigwig_chromosome,
                    interval_start,
                    clipped_end,
                    type="mean",
                )[0]

                signal_arrays[
                    signal_name
                ][row_number] = (
                    0.0
                    if value is None
                    else float(value)
                )

    finally:
        for handle in handles.values():
            handle.close()

    output = TE_table.copy()

    for signal_name, values in signal_arrays.items():
        output[signal_name] = values

    return output


def package_version(package_name: str) -> str:
    """Return an installed package version."""
    try:
        return importlib.metadata.version(
            package_name
        )
    except importlib.metadata.PackageNotFoundError:
        return "unknown"


# ==============================================================================
# 3. Validate inputs and parse protein-coding TSS positions
# ==============================================================================

for input_file in (
    H3K9_1KB_TABLE,
    PROTEIN_CODING_GTF,
    TE_ANNOTATION_BED,
    H3K9_SPERMATOCYTE_BIGWIG,
    H3K9_WING_BIGWIG,
    TE_EXPRESSION_BIGWIG,
):
    require_file(input_file)

TSS_by_chromosome = parse_gene_tss(
    PROTEIN_CODING_GTF
)


# ==============================================================================
# 4. Delta H3K9me2 by distance from 1-kb bins to the nearest TSS
# ==============================================================================

H3K9_bins = pd.read_csv(
    H3K9_1KB_TABLE
)

required_bin_columns = {
    "chr",
    "bin_mid",
    "h3k9_delta",
    "region",
}

missing_bin_columns = (
    required_bin_columns
    - set(H3K9_bins.columns)
)

if missing_bin_columns:
    raise ValueError(
        "The 1-kb H3K9 table is missing required columns: "
        + ", ".join(
            sorted(
                missing_bin_columns
            )
        )
    )

H3K9_bins["chr"] = (
    H3K9_bins["chr"]
    .map(canonical_chromosome)
)

H3K9_bins["dist_tss"] = add_nearest_tss_distance(
    data=H3K9_bins,
    chromosome_column="chr",
    position_column="bin_mid",
    TSS_by_chromosome=TSS_by_chromosome,
)

H3K9_bins["distance_bin"] = pd.cut(
    H3K9_bins["dist_tss"],
    bins=DISTANCE_BREAKS_BP,
    labels=DISTANCE_LABELS,
    right=False,
    include_lowest=True,
)

H3K9_bins.to_csv(
    OUTPUT_DIR
    / "H3K9_delta_1kb_bins_with_TSS_distance.csv",
    index=False,
)

H3K9_distance_summary = (
    H3K9_bins[
        H3K9_bins["region"].isin(
            ("Eu", "PCH")
        )
    ]
    .groupby(
        [
            "region",
            "distance_bin",
        ],
        observed=True,
    )
    .agg(
        n_bins=(
            "h3k9_delta",
            "size",
        ),
        mean_delta_H3K9me2=(
            "h3k9_delta",
            "mean",
        ),
        median_delta_H3K9me2=(
            "h3k9_delta",
            "median",
        ),
    )
    .reset_index()
)

H3K9_distance_summary.to_csv(
    OUTPUT_DIR
    / "H3K9_delta_by_TSS_distance_Eu_PCH.csv",
    index=False,
)


# ==============================================================================
# 5. Prepare the TE-level table
# ==============================================================================

TE_table = parse_TE_annotation(
    TE_ANNOTATION_BED
)

TE_table = TE_table[
    TE_table["chr"].isin(
        TARGET_CHROMOSOMES
    )
].copy()

if TE_table.empty:
    raise ValueError(
        "No TE loci remained after chromosome filtering."
    )

TE_table["dist_tss"] = add_nearest_tss_distance(
    data=TE_table,
    chromosome_column="chr",
    position_column="midpoint",
    TSS_by_chromosome=TSS_by_chromosome,
)

compartment_assignments = np.full(
    len(TE_table),
    None,
    dtype=object,
)

for chromosome, row_indices in TE_table.groupby(
    "chr",
    sort=False,
).indices.items():
    row_indices = np.asarray(
        row_indices,
        dtype=int,
    )

    compartment_assignments[
        row_indices
    ] = assign_compartment(
        chromosome=str(chromosome),
        positions=TE_table.iloc[
            row_indices
        ][
            "midpoint"
        ].to_numpy(
            dtype=np.int64
        ),
    )

TE_table["region"] = compartment_assignments

TE_table = TE_table[
    TE_table["region"].isin(
        COMPARTMENT_ORDER
    )
].copy()

TE_table.reset_index(
    drop=True,
    inplace=True,
)

TE_table = extract_interval_signals(
    TE_table=TE_table,
    bigwig_paths={
        "h3k9_sperm": H3K9_SPERMATOCYTE_BIGWIG,
        "h3k9_wing": H3K9_WING_BIGWIG,
        "te_expr_cpm": TE_EXPRESSION_BIGWIG,
    },
)

TE_table["h3k9_delta"] = (
    TE_table["h3k9_sperm"]
    - TE_table["h3k9_wing"]
)

TE_table["distance_bin"] = pd.cut(
    TE_table["dist_tss"],
    bins=DISTANCE_BREAKS_BP,
    labels=DISTANCE_LABELS,
    right=False,
    include_lowest=True,
)

TE_table["H3K9me2_change_group"] = np.where(
    TE_table["h3k9_delta"] >= 0,
    "Gain/stable",
    "Loss",
)

TE_table.to_csv(
    OUTPUT_DIR
    / "TE_loci_with_H3K9_TSS_distance_expression.csv",
    index=False,
)


# ==============================================================================
# 6. TE expression by TSS distance and H3K9me2-change group
# ==============================================================================

TE_expression_summary = (
    TE_table
    .groupby(
        [
            "distance_bin",
            "H3K9me2_change_group",
        ],
        observed=True,
    )
    .agg(
        n_TE_loci=(
            "te_expr_cpm",
            "size",
        ),
        mean_TE_CPM=(
            "te_expr_cpm",
            "mean",
        ),
        median_TE_CPM=(
            "te_expr_cpm",
            "median",
        ),
    )
    .reset_index()
)

TE_expression_summary.to_csv(
    OUTPUT_DIR
    / "TE_expression_by_TSS_distance_and_H3K9_change.csv",
    index=False,
)


# ==============================================================================
# 7. Proximal-versus-distal test among expressed TE loci
# ==============================================================================

expressed_TE = TE_table[
    np.isfinite(
        TE_table["te_expr_cpm"]
    )
    & (
        TE_table["te_expr_cpm"]
        > 0
    )
].copy()

proximal_TE = expressed_TE[
    expressed_TE["dist_tss"]
    < PROXIMAL_DISTANCE_BP
].copy()

distal_TE = expressed_TE[
    expressed_TE["dist_tss"]
    > DISTAL_DISTANCE_BP
].copy()

proximal_values = proximal_TE[
    "h3k9_delta"
].replace(
    [np.inf, -np.inf],
    np.nan,
).dropna()

distal_values = distal_TE[
    "h3k9_delta"
].replace(
    [np.inf, -np.inf],
    np.nan,
).dropna()

if (
    len(proximal_values) == 0
    or len(distal_values) == 0
):
    raise ValueError(
        "The proximal-versus-distal comparison contains an empty group."
    )

Mann_Whitney_result = mannwhitneyu(
    proximal_values,
    distal_values,
    alternative="two-sided",
    method="auto",
)

proximal_distal_test = pd.DataFrame(
    [
        {
            "comparison": (
                f"Expressed TE loci <{PROXIMAL_DISTANCE_BP} bp "
                f"vs >{DISTAL_DISTANCE_BP} bp from the nearest TSS"
            ),
            "n_proximal": len(
                proximal_values
            ),
            "n_distal": len(
                distal_values
            ),
            "mean_delta_H3K9me2_proximal": float(
                proximal_values.mean()
            ),
            "mean_delta_H3K9me2_distal": float(
                distal_values.mean()
            ),
            "median_delta_H3K9me2_proximal": float(
                proximal_values.median()
            ),
            "median_delta_H3K9me2_distal": float(
                distal_values.median()
            ),
            "median_difference_proximal_minus_distal": float(
                proximal_values.median()
                - distal_values.median()
            ),
            "Mann_Whitney_U": float(
                Mann_Whitney_result.statistic
            ),
            "p_value_two_sided": float(
                Mann_Whitney_result.pvalue
            ),
        }
    ]
)

proximal_distal_test.to_csv(
    OUTPUT_DIR
    / "expressed_TE_proximal_vs_distal_H3K9_test.csv",
    index=False,
)

proximal_TE.to_csv(
    OUTPUT_DIR
    / "expressed_TE_proximal_under_2kb.csv",
    index=False,
)

distal_TE.to_csv(
    OUTPUT_DIR
    / "expressed_TE_distal_over_20kb.csv",
    index=False,
)


# ==============================================================================
# 8. Save parameters and software versions
# ==============================================================================

analysis_parameters = pd.DataFrame(
    {
        "parameter": [
            "Input 1-kb H3K9me2 table",
            "Protein-coding GTF",
            "TE annotation",
            "Spermatocyte H3K9me2 bigWig",
            "Wing H3K9me2 bigWig",
            "TE-expression bigWig",
            "TE coordinate convention",
            "H3K9me2 delta definition",
            "H3K9me2 gain/stable definition",
            "H3K9me2 loss definition",
            "Proximal TE definition",
            "Distal TE definition",
            "Expressed TE definition",
            "Proximal-distal test",
        ],
        "value": [
            str(H3K9_1KB_TABLE),
            str(PROTEIN_CODING_GTF),
            str(TE_ANNOTATION_BED),
            str(H3K9_SPERMATOCYTE_BIGWIG),
            str(H3K9_WING_BIGWIG),
            str(TE_EXPRESSION_BIGWIG),
            (
                "1-based inclusive"
                if TE_COORDINATES_ARE_ONE_BASED_INCLUSIVE
                else "0-based half-open"
            ),
            "Spermatocyte RPGC - wing RPGC",
            "Delta H3K9me2 >= 0",
            "Delta H3K9me2 < 0",
            f"Distance to nearest TSS < {PROXIMAL_DISTANCE_BP} bp",
            f"Distance to nearest TSS > {DISTAL_DISTANCE_BP} bp",
            "Mean TE-expression bigWig signal across locus > 0",
            "Two-sided Mann-Whitney U",
        ],
    }
)

analysis_parameters.to_csv(
    OUTPUT_DIR
    / "analysis_parameters.csv",
    index=False,
)

software_versions = pd.DataFrame(
    {
        "software": [
            "Python",
            "numpy",
            "pandas",
            "pyBigWig",
            "scipy",
        ],
        "version": [
            sys.version.replace("\n", " "),
            package_version("numpy"),
            package_version("pandas"),
            package_version("pyBigWig"),
            package_version("scipy"),
        ],
    }
)

software_versions.to_csv(
    OUTPUT_DIR
    / "software_versions.csv",
    index=False,
)


# ==============================================================================
# 9. Final summary
# ==============================================================================

print("\nH3K9me2 TSS-distance analysis complete.")
print(f"Results were written to: {OUTPUT_DIR}")

print("\nDelta H3K9me2 by TSS-distance bin:")
print(
    H3K9_distance_summary.to_string(
        index=False
    )
)

print("\nExpressed-TE proximal-versus-distal test:")
print(
    proximal_distal_test.to_string(
        index=False
    )
)
